(xbindkey '(XF86MonBrightnessUp) "xbacklight -inc 20")
(xbindkey '(XF86MonBrightnessDown) "xbacklight -dec 20")
(xbindkey '(XF86Tools) "$HOME/dotfiles/scripts/toggletouchpad.sh")
(xbindkey '(Control+Alt + Next) "mpc next")
(xbindkey '(Control+Alt + Prior) "mpc prev")
(xbindkey '(Control+Alt + End) "mpc toggle")
(xbindkey '(Control+Alt + Home) "mpc stop")
