(xbindkey '(XF86MonBrightnessUp) "xbacklight -inc 20")
(xbindkey '(XF86MonBrightnessDown) "xbacklight -dec 20")
(xbindkey '(XF86Tools) "$HOME/dotfiles/scripts/toggletouchpad.sh")
(xbindkey '(control alt Next) "mpc next")
(xbindkey '(control alt Prior) "mpc prev")
(xbindkey '(control alt End) "mpc toggle")
(xbindkey '(control alt Home) "mpc stop")
